version: '3.8'
services:
  db:
    image: postgres:15
    container_name: api-db
    restart: always
    ports:
      - '5450:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: projectdb