
version: '3.1'

services:
  db:
    build: .
    container_name: api-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes: # link with container to continue the data from the container in the pc
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=projectdb